### ISSUE TITLE
How to Make a new page inside the home page

### ISSUE THREAD

**Issue by xliu3** [HL7/genomics-unified#1]
Wonder what are the steps to make a new page with a link in the home page @lmckenzi

**Comment by lmckenzi** [comment]
The new page you posted seems sort of like an appendix to me, so we can maybe label and organize it as such.  You'll just need to update the index.xml file to include a link to it.

**Comment by cerkyp** [comment]
Not a big deal at this point as we still have to review all of the HTML content, but I do want to ask a question regarding the new page you added.  I am not sure that information is needed in our IG?  I am not sure how referencing SMART apps and published papers will help an implementer (or anyone) understand this IG, especially when those apps and papers don't reflect the content of this IG?  Meaning, they were all developed/written on a much older and now out-of-date way to deliver genomic results in FHIR.

**Comment by lmckenzi** [comment]
It may not be an issue to have an appendix that talks about some of the
history - some may be interested.  But we'll need to clearly distinguish
what content is necessary/relevant to implementing the IG and what isn't.
It'll also need to be clear if we're referencing something that's not
compliant with the current IG.

*Lloyd McKenzie*, P.Eng.
Senior Consultant, Information Technology Services
Gevity Consulting Inc.

 E: lmckenzie@gevityinc.com
M: +1 587-334-1110 <1-587-334-1110>
W: gevityinc.com


*GEVITY**Enabling a healthier world *

CONFIDENTIALITY – This communication is confidential and for the exclusive
use of its intended recipients. If you have received this communication
through error, please notify the sender and delete the message without
copying or disclosing*.*

REPRESENTATION –  Unless explicitly stated otherwise, the opinions and
positions expressed in this e-mail do not necessarily reflect those of my
employer, my clients nor the organizations with whom I hold governance
positions

**Comment by cerkyp** [comment]
I guess there is some value in the history, but that will be a slippery slope as to what to include in that history and what not too.  But delivered via an appropriately caveated appendix is fine.
