### ISSUE TITLE
Warnings on the build

### ISSUE THREAD

**Issue by cerkyp** [HL7/genomics-unified#3]
@lmckenzi - I am seeing the **following** warnings on the build.  Should we be concerned?

process res: diagnosticreport                                                    (25.0790sec)
**Business version mismatch** in /scratch/ig-build-temp-00PFNW/repo/src/resources/diagnosticreport-profile-spreadsheet - overriding from 0.01 to test
process res: medicationstatement                                                 (25.0901sec)
**Business version mismatch** in /scratch/ig-build-temp-00PFNW/repo/src/resources/medicationstatement-profile-spreadsheet - overriding from 0.01 to test

**Comment by lmckenzi** [comment]
No.  It means that the version number in the spreadsheets and the version number we're asserting in the configuration file are different, but that's not an issue.  We could make them the same to suppress the warnings, but the fact the config file is overriding what's in the spreadsheet is intentional.

**Comment by cerkyp** [comment]
OK, thanks.
